source 'https://rubygems.org'

# Specify the CocoaPods version
gem 'cocoapods', '~> 1.14.0'

# Add other gems if needed
gem 'ffi', '~> 1.15.0' # Required for some native dependencies
gem 'xcodeproj', '~> 1.22.0' # For Xcode project manipulation